### ISSUE TITLE
ImmunoSeq Conversion

### ISSUE THREAD

**Issue by mgchavez** [mikessh/vdjtools#77] opened 2017-06-13 17:37 UTC
I have been trying to input my ImmunoSeq data using Convert but every time I run it, I get the error "Some mandatory columns are absent in the input file". I have tried both immunoseq and immunoseqv2 softwares and tried it on the Spreafico et al data but keep getting this message.

**Comment by mikessh** [comment] 2017-06-14 05:21
Hello,

The test files for checking immunoseq conversion are here: https://github.com/mikessh/vdjtools/tree/master/src/test/resources/samples

They are called ``immunoseq.txt.gz`` and ``immunoseqv2.txt.gz``. You can compare your input file with them to see the difference that prevents the conversion.

Upon closer inspection of the error log (I haven't seen the input table header, please send me if you can), I suggest that the problem is that the count in your file appears in the ``templates`` column, not ``reads`` column that is used by vdjtools. 

Also, your format appears to be ``immunoseq``, first version (the one that has ``_`` instead of camel casing in header).

Can you please try replacing your vdjtools jar with [this one](https://github.com/mikessh/vdjtools/files/1073577/vdjtools-1.1.5-SNAPSHOT.jar.zip) and try once again?

N.B. Looks like there will be many clonotypes with "N" nucleotides in the end of nucleotide CDR3 sequence. This is because immunoseq uses short reads and then guesses the J part. This may be resolved in future using MIXCR re-mapping and extension (we have quite nice results with highly fragmented reads from RNA-SEQ).

**Closed** 2017-06-15 11:54 UTC
